### ISSUE TITLE
How to avoid garbled Chinese characters

### ISSUE THREAD

**Issue by hackerBaiDan** [icfly2/neographviz#5]
![image](https://user-images.githubusercontent.com/53365080/120784215-71191900-c55e-11eb-9f65-27a04cfe763d.png)

**Comment by icfly2** [comment]
Thank's for filing this issue, could you give a bit more details please?

For example a minimum graph defintion for Neo4j?

What characters does it show? And which one's fail? I'm afraid I don't read or write Chinese.

**Comment by hackerBaiDan** [comment]
> Thank's for filing this issue, could you give a bit more details please?
> 
> For example a minimum graph defintion for Neo4j?
> 
> What characters does it show? And which one's fail? I'm afraid I don't read or write Chinese.

![image](https://user-images.githubusercontent.com/53365080/120946935-c593e280-c770-11eb-9021-d69d522b8289.png)
![image](https://user-images.githubusercontent.com/53365080/120947173-700c0580-c771-11eb-8697-0aa9f0ee8ad9.png)

Thank's for replying this issue and helping me.  The first picture is the field I got from neo4j database, and the contents framed are the Chinese characters I want to display. The second picture is the one I use neographviz to display. The contents in the box are garbled Chinese characters. If the Chinese characters are not displayed correctly, I don't know how to solve it. If I follow the solution of garbled Chinese characters in graphviz, will it work?

**Comment by hackerBaiDan** [comment]
Maybe modifying the display font can solve my problem. May I customize the font, please？

**Comment by hackerBaiDan** [comment]
Hi,

> 

Hi,icfly2.GOOD INFOMATION.
I read and write the text encoding properties in the generated HTML again, and then I will not be random code again. Thank you for your attention.
