### ISSUE TITLE
No data selected

### ISSUE THREAD

**Issue by hackerBaiDan** [icfly2/neographviz#6]
![image](https://user-images.githubusercontent.com/53365080/121119651-9784d000-c84e-11eb-92e4-fc2703b44dc6.png)![image](https://user-images.githubusercontent.com/53365080/121119736-c438e780-c84e-11eb-97e2-ce7aff271688.png)![image](https://user-images.githubusercontent.com/53365080/121119707-b2efdb00-c84e-11eb-8001-08bbbd11e74d.png)
When I query the core node, there is data, but no data is generated. I don't know why, can I use plot (graph, query) to draw relevant HTML?

**Comment by icfly2** [comment]
Ok, i've just found a similar bug, is it possible that you have duplicate nodes in the the list of nodes? Cypher returns them as duplicated sometimes.
Compare:
`list({v["id"]: v for v in nodes}.values())` vs `nodes`

I'll make a fix for this in `get_nodes` if i can confirm that this fixes the issue.
